version: '3.8'
services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "camp3rjake"
      MYSQL_DATABASE: FamilyChoreTV
      MYSQL_USER: remote
      MYSQL_PASSWORD: "camp3rjake"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  api:
    build: .
    image: familychoretv-api:latest
    container_name: familychoretv-api
    environment:
      DB_HOST: mariadb-mariadb-1
      DB_USER: remote
      DB_PASSWORD: "camp3rjake"
      DB_NAME: FamilyChoreTV
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    command: sh -c "npm install bcryptjs && npm install && node server.js"

volumes:
  mariadb_data:
